import type { Metadata } from "next";
import "./styles/globals/globals.scss";
import { AppProvider } from '@/context/AppContext';
import Header from "./blocks/header/Header";
import { fetchMenuData } from "@/lib/api";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const menuItems = await fetchMenuData();

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/onl5exr.css" />
      </head>
      <body>
        <AppProvider>
          <header>
            <Header menuItems={menuItems}/>
          </header>
          <main>
            {children}
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
